[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = ".." }
pollster = "0.3.0"
egui = "0.24.1"
env_logger = "0.11.2"
rfd = "0.14.0"